### ISSUE TITLE
Encountered missing dependencies: tasty >=0.11 && <1.2

### ISSUE THREAD

**Issue by ghost** [LaurentRDC/hakyll-images#2]
Setup: Encountered missing dependencies:
tasty >=0.11 && <1.2

tasty is 1.2 now on hackage. Please fix.

**Comment by LaurentRDC** [comment]
@gnidorah Thank you for pointing this out. I have relaxed the dependency bounds on tasty and other dependencies of the test suite.

I have edited the Hackage package metadata for hakyll-images 0.4.0, 0.4.1, and 0.4.2 (latest). Please update your package index before trying to install again. Let me know if the issue is fixed for you.

**Comment by ghost** [comment]
@LaurentRDC It builds now, thank you much!
